<?php
$libro = [
    [
        "id" => "libro1",
        "titolo" => "L'Ombra degli dei",
        "autore" => "di John Gwynne",
        "foto" => "ombraDegliDei.jpg",
        "genere" => "Romanzo Fantasy",
        "descrizione" => " La storia è un'epica fantasy incentrata su una imminente guerra tra forze del bene e del male. Con personaggi sfaccettati, intrighi politici, magia e battaglie epiche, la trama esplora temi come il destino e il libero arbitrio.",
        "prezzo" => 19.00,
        "quantita" => 5,
    ],
    [
        "id" => "libro2",
        "titolo" => "The Outsider",
        "autore" => "di Stephen King",
        "foto" => "outsider.jpg",
        "genere" => "Romanzo Horror",
        "descrizione" => "É un thriller che inizia con l'arresto di un uomo rispettabile per un omicidio. Procede con delle indagini, tuttavia si evolve in un mistero sovrannaturale che sfida la realtà.",
        "prezzo" => 12.90,
        "quantita" => 5,
    ],
    [
        "id" => "libro3",
        "titolo" => "Il Gigante del Campetto",
        "autore" => "di Gigi Datome",
        "foto" => "giganteDelCampetto.jpg",
        "genere" => "Fumetto",
        "descrizione" => "Cesare e Gianna si allenano all'alba al campetto per giocare a basket. Incontrano un gigante che diventa il compagno di squadra. Imparano che per avere successo nello sport serve coraggio e fiducia nei compagni.",
        "prezzo" => 14.90,
        "quantita" => 5,
    ],
    [
        "id" => "libro4",
        "titolo" => "Le 39 chiavi",
        "autore" => "di Rick Riordan",
        "foto" => "chiavi39.jpg",
        "genere" => "Romanzo d'avventura",
        "descrizione" => "Amy e Dan Cahill, chiamati per la lettura del testamento della nonna Grace, devono scegliere tra un'eredità milionaria e il primo indizio per svelare il segreto di famiglia. Accettano la sfida e si lanciano in una pericolosa caccia al tesoro globale per conquistare il potere delle 39 chiavi.",
        "prezzo" => 20.90,
        "quantita" => 5,
    ],
    [
        "id" => "libro5",
        "titolo" => "La scomparsa di Stephanie Mailer",
        "autore" => "di Joël Dicker",
        "foto" => "scomparsaStephanie.jpeg",
        "genere" => "Romanzo Giallo",
        "descrizione" => "Si sviluppa intorno alla misteriosa sparizione di una giornalista durante una festa in una piccola città. Anni dopo, una lettera anonima mette in discussione la verità dei fatti, riaprendo un'indagine che svela segreti scioccanti e intrighi nascosti.",
        "prezzo" => 14.25,
        "quantita" => 5,
    ],
    [
        "id" => "libro6",
        "titolo" => "Il barone rampante",
        "autore" => "di Italo Calvino",
        "foto" => "italoCalvino.jpg",
        "genere" => "Romanzo Classico",
        "descrizione" => "Racconta la storia di Cosimo, un giovane barone del XVIII secolo che decide di trascorrere la sua vita sugli alberi. Attraverso avventure straordinarie e incontri singolari, il romanzo esplora temi come la libertà individuale, la ribellione e la ricerca di un significato nella vita.",
        "prezzo" => 11.90,
        "quantita" => 5,
    ],
]
?>